### ISSUE TITLE
Support for promises

### ISSUE THREAD

**Issue by ghost** [gulpjs/vinyl-contents#1]
Would it be possible to add support for promises? This would make it significantly easier to use  in my code base.

I can fire up a pull request if you want; I just have to make sure that the old API still works.

**Comment by phated** [comment]
Mixing promises inside of streams just asks for a world of trouble, so I don't think this should be implemented.

To demonstrate this, can you spot the bug here?
```js
through2(async function(file, _, cb) {
    try {
        var contents = await vinylContents(file);
        // do stuff that might throw an error
        cb(null, file);
    } catch (err) {
        cb(err);
    }
})
```

The problem here is that the top level `async function` doesn't bind to the returned promise, so if an error (including syntax errors) is thrown inside any `on('error')` handler on the stream, you end up with an unhandled rejection in this callback.

All that to say that mixing streams and promises is a bad idea.
